project_id = "vyijbdrvixngzklwgdsw"

[functions.send-notification]
verify_jwt = false

[functions.send-feedback]
verify_jwt = false

[functions.auth-rate-limit]
verify_jwt = false

[functions.send-lockout-notification]
verify_jwt = false